language: java

jdk:
  - oraclejdk8

script: mvn clean install

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    local_dir: dpl_cd_upload
    skip_cleanup: true
    on: &1
      repo: DilipKunderu/SetWebService
    bucket: war-bucket
    region: us-west-1
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: war-bucket
    key: latest.zip
    bundle_type: zip
    application: set-impl
    deployment_group: IntuitDeploymentGroup
    region: us-west-1
    on: *1
    wait-until-deployed: true