language: java

script:
  mvn clean install

before_deploy:
  - zip -r temp.zip abstractset-0.0.1-SNAPSHOT.war appspec.yml runas.sh || true
  - mkdir -p "uploadDir"
  - mv temp.zip uploadDir/temp.zip || true

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    local_dir: uploadDir
    skip_cleanup: true
    on: &2
      repo: DilipKunderu/SetWebService
    bucket: war-bucket
    region: us-west-1
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: war-bucket
    key: abstractset-0.0.1-SNAPSHOT.war
    bundle_type: zip
    application: set-impl
    deployment_group: IntuitDeploymentGroup
    region: us-west-1
    on: *2
    wait-until-deployed: true